### ISSUE TITLE
Walidacja dla POST /persons

### ISSUE THREAD

**Issue by yarpo** [JediSebas/RestAPI#7]
Dodać walidację do wszystkich pól dla obiektu PersonDetails.

wszystkie -> mandatory
first name i last name - długość nie większa niż długość kolumny w bd
email - walidacja emaila
address - długość nie większa niż długość kolumny w bd

**Comment by JediSebas** [comment]
PR:
https://github.com/JediSebas/RestAPI/pull/14

**Comment by yarpo** [comment]
Dodaj uni testy dla samej walidacji. Zarówno na poziomie unit testów, jak mockMvc

**Comment by JediSebas** [comment]
Nie bardzo wiem, jak z mockMvc mógłbym zrobić test dla walidacji
